plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

version = "mc${minecraft_version}-NeoForge-${mod_version}"
group = project.maven_group
var realVersion = project.mod_version + '+neoforge'

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven { url "https://api.modrinth.com/maven" }
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

tasks.withType(JavaExec).configureEach {
    executable = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(25)
    }.get().executablePath.asFile.absolutePath
}

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
        data {
            serverData()
            programArguments = [
                    '--mod', project.mod_id,
                    '--all',
                    '--output', file('src/generated/resources').absolutePath,
                    '--existing', file('src/main/resources').absolutePath
            ]
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    implementation "maven.modrinth:kiwi:${project.kiwi_version}+neoforge"
    annotationProcessor "maven.modrinth:kiwi:${project.kiwi_version}+neoforge"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude("/assets/${project.mod_id}/lang/en_us.existing.json")
    exclude('**/*.py')
    from('LICENSE') {
        rename { "${it}_${project.archives_base_name}" }
    }
    manifest {
        attributes([
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : realVersion,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}

publishMods {
    file = jar.archiveFile
    changelog = file('CHANGELOG.md').exists() ? file('CHANGELOG.md').text : ''
    type = ['release': STABLE, 'beta': BETA, 'alpha': ALPHA][release_type]
    modLoaders.add('neoforge')
    displayName = "[NeoForge ${supported_version}] ${mod_version}"
    version = realVersion

    curseforge {
        projectId = '379887'
        accessToken = providers.environmentVariable('CURSE_TOKEN')
        minecraftVersions.add(minecraft_version)
        requires('kiwi')
        optional('cloth-config')
    }
    modrinth {
        projectId = 'uaLW6JVR'
        accessToken = providers.environmentVariable('MODRINTH_TOKEN')
        minecraftVersions.add(minecraft_version)
        requires('kiwi')
        optional('cloth-config')
    }
}
