# Build defaults. Override with GRADLE_OPTS when necessary.
org.gradle.jvmargs=-Xms64m -Xmx2G -Dfile.encoding=UTF-8 -Duser.language=en
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=26.2
archive_minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.19

mod_version=26.2.0
mod_id=passablefoliage
maven_group=snownee.passablefoliage
archives_base_name=PassableFoliage

# Dependencies
fabric_version=0.158.0+26.2
