name: Bug report or suggestion
description: Report one problem or idea per issue
body:
  - type: dropdown
    id: modloader
    attributes:
      label: Mod loader
      options:
        - Please select
        - Fabric
        - Quilt
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft version
      placeholder: eg. 26.2
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Mod version
      placeholder: eg. 26.2.0
    validations:
      required: true
  - type: input
    id: modloader-version
    attributes:
      label: Modloader version
      description: |
        List the version of the mod loader you are using.
        If on Fabric, post the versions of both Fabric Loader and Fabric API.
      placeholder: "eg. Fabric Loader 0.19.3 + Fabric API 0.158.0"
    validations:
      required: true
  - type: input
    id: modpack
    attributes:
      label: Modpack info
      description: |
        If you are playing a modpack, post the link to it!
  - type: checkboxes
    id: reproducible
    attributes:
      label: "[IMPORTANT] If bug:"
      options:
        - label: "I confirmed that this bug is reproducible on a minimal setup, not only in a large modpack."
  - type: input
    attributes:
      label: "[IMPORTANT] If bug: The **latest.log** file, not the crash report"
      description: "Please use a paste site such as [gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc."
  - type: textarea
    attributes:
      label: Issue description
      placeholder: A description of the bug/suggestion.
